n = input('Digite algo: ')
print(n.isalnum())
print(n.isalpha())
print(n.isdecimal())
print(n.isdigit())
print(n.islower())
print(n.isnumeric())
print(n.isascii())
print(n.isprintable())
print(n.isspace())
print(n.istitle())
print(n.isupper())
